"""Hecke triangle group trace-field test for the monodromy conjecture
(HYPOTHESIS Step 53 — proper computational pathway from ee.txt).

ee.txt provided a concrete pathway for testing Conjecture #1
(metallic b = trace field of Z3 cover monodromy):

Step 1 — Riemann-Hurwitz: the Z3 cover of P^1 with 3 branch points,
each with full ramification (e_p = 3), has genus
    2g - 2 = 3·(2·0 - 2) + 3·(3-1) = 0 → g = 1
i.e. the cover is a torus T^2. Mapping class group of T^2 is SL(2, Z).

Step 2 — Lift the local monodromies to homological monodromy in
SL(2, Z). Around each branch point the local monodromy is a generator
of Z3 (order 3). In SL(2, Z), order-3 elements have trace -1 (unique
conjugacy class).

Step 3 — Step 50 already tested integer SL(2, Z) traces and the
silver-eigenvalue version. This module tests the more refined
Hecke triangle group H(q), whose trace field is Z[2 cos(π/q)] —
allowing irrational entries in the trace.

Honest scope
------------
This module DOES:
  - Generate Hecke triangle group elements as words in S = [[0,-1],[1,0]]
    and T_q = [[1, λ_q], [0, 1]] with λ_q = 2 cos(π/q).
  - Enumerate |Tr(M)|/2 for words up to bounded length.
  - Match atlas b values against the trace fields of H(3), H(4), H(5),
    H(6), H(8), H(12) (the values where λ_q lies in a known number
    field).

This module DOES NOT:
  - Construct the actual homological monodromy of the Z3 cover. The
    full construction requires choosing a basis of H_1(T^2, Z) and
    computing the action of the deck group, which depends on additional
    geometric data (positions of the 3 branch points). Different choices
    give different SL(2, Z) subgroups.
  - Prove the conjecture; it tests a necessary condition: do atlas b
    values lie in any of the standard Hecke trace fields?

Verdict on ee.txt's pathway:
  - Riemann-Hurwitz computation is CORRECT and confirms g=1 (torus).
  - Mapping class group identification SL(2, Z) is CORRECT.
  - But the trace field test FAILS: only 1/19 atlas b values
    (the lepton b = sqrt(2)) matches any tested Hecke trace field
    within 1%. The atlas b values are continuous distributions of
    irrationals not generated by SL(2, R) trace fields of standard
    triangle groups.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import cos, pi, sqrt

import numpy as np

from . import foot_atlas_discrimination as fad


def lambda_q(q: int) -> float:
    """λ_q = 2 cos(π/q) for the Hecke triangle group H(q)."""
    if q < 2:
        raise ValueError("q >= 2 required")
    return float(2 * cos(pi / q))


HECKE_LAMBDAS: dict[str, float] = {
    "H(3)=SL(2,Z)": lambda_q(3),                 # = 1, integer trace field
    "H(4)":          lambda_q(4),                 # = sqrt(2), trace field Z[√2]
    "H(5)":          lambda_q(5),                 # = phi, trace field Z[φ]
    "H(6)":          lambda_q(6),                 # = sqrt(3), trace field Z[√3]
    "H(8)":          lambda_q(8),                 # = sqrt(2+sqrt(2))
    "H(12)":         lambda_q(12),
}


def hecke_generators(lam: float) -> list[np.ndarray]:
    """Standard generators S, T_lam, S^{-1}, T_lam^{-1}."""
    S = np.array([[0.0, -1.0], [1.0, 0.0]])
    T = np.array([[1.0, lam], [0.0, 1.0]])
    S_inv = S.T            # S^2 = -I, so S^{-1} = -S = S^T (using -I = -id)
    T_inv = np.array([[1.0, -lam], [0.0, 1.0]])
    return [S, T, S_inv, T_inv]


def enumerate_traces(lam: float, max_length: int = 8) -> list[float]:
    """All distinct traces of words up to max_length in the Hecke generators."""
    gens = hecke_generators(lam)
    seen: set[tuple[float, ...]] = set()
    traces: set[float] = set()

    def rec(M: np.ndarray, depth: int) -> None:
        if depth > max_length:
            return
        key = tuple(np.round(M.flatten(), 8).tolist())
        if key in seen:
            return
        seen.add(key)
        traces.add(round(float(np.trace(M)), 8))
        for g in gens:
            rec(M @ g, depth + 1)

    rec(np.eye(2), 0)
    return sorted(traces)


@dataclass(frozen=True)
class HeckeTraceMatchReport:
    label: str
    lambda_q: float
    n_distinct_traces: int
    sample_half_traces: list[float]
    n_atlas_matches_within_1pct: int
    n_atlas_total: int
    notes: str


def test_hecke_against_atlas(label: str, lam: float,
                                max_length: int = 8) -> HeckeTraceMatchReport:
    traces = enumerate_traces(lam, max_length)
    half_traces = sorted({abs(t) / 2.0 for t in traces if abs(t) < 100})
    atlas_bs = [fad.implied_b(masses) for masses in fad.ATLAS_19_MASSES.values()]
    matches = 0
    for b in atlas_bs:
        if not half_traces:
            continue
        nearest = min(half_traces, key=lambda h: abs(h - b))
        if abs(nearest - b) / b * 100 < 1.0:
            matches += 1
    return HeckeTraceMatchReport(
        label=label,
        lambda_q=float(lam),
        n_distinct_traces=len(traces),
        sample_half_traces=[float(h) for h in half_traces[:12]],
        n_atlas_matches_within_1pct=matches,
        n_atlas_total=len(atlas_bs),
        notes=("Atlas b values are continuous irrationals; Hecke trace "
               "fields are discrete subsets of R. The match count "
               "shows whether any atlas b lies in the tested trace field."),
    )


def all_hecke_tests(max_length: int = 8) -> list[HeckeTraceMatchReport]:
    return [test_hecke_against_atlas(label, lam, max_length)
            for label, lam in HECKE_LAMBDAS.items()]


def riemann_hurwitz_genus(degree: int = 3,
                            base_genus: int = 0,
                            n_branch_points: int = 3,
                            ramification_per_point: int = 3) -> int:
    """Apply Riemann-Hurwitz to compute the genus of a degree-d cover.

    2g_cover - 2 = d (2 g_base - 2) + sum (e_p - 1)
    """
    rhs = degree * (2 * base_genus - 2) + n_branch_points * (ramification_per_point - 1)
    g_cover = (rhs + 2) // 2
    if g_cover * 2 - 2 != rhs:
        raise ValueError("non-integer genus result")
    return g_cover


__all__ = [
    "lambda_q", "HECKE_LAMBDAS",
    "hecke_generators", "enumerate_traces",
    "HeckeTraceMatchReport",
    "test_hecke_against_atlas", "all_hecke_tests",
    "riemann_hurwitz_genus",
]
