"""Topological seesaw scaffold for neutrino masses (HYPOTHESIS Step 43).

Honest scope
------------
This module DOES:
  - Implement the standard seesaw formula m_nu = m_D^T M_R^-1 m_D
    with m_D = v * y_nu (Dirac mass) and M_R = M_0 * A^(-2 winding)
    (right-handed Majorana mass scaling with winding).
  - Compute the resulting light neutrino spectrum and sum, given
    inputs (v, M_0, A, y_nu_pattern).
  - Show that any observed sum_m_nu is reachable by tuning M_0.

This module DOES NOT:
  - Predict M_0 from the framework. Grok claimed M_R ~ 1e14-1e15 GeV
    "naturally generated by finite Möbius temporal loop"; in fact
    M_0 is a free input.
  - Derive y_nu_pattern from the polar wavefunctions.

Verdict: TUNABLE. The 0.059 eV "match" requires choosing M_0 to fit.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class SeesawSpectrum:
    v_GeV: float
    M_0_GeV: float
    A: float
    y_nu_pattern: tuple[float, float, float]
    light_masses_eV: tuple[float, float, float]
    sum_m_nu_eV: float
    delta_m21_squared_eV2: float
    delta_m31_squared_eV2: float
    notes: str


def light_neutrino_spectrum(v_GeV: float = 246.22,
                              M_0_GeV: float = 1e14,
                              A: float = 0.48,
                              y_nu_pattern: tuple[float, float, float] = (1.0, 1.0, 1.0)
                              ) -> SeesawSpectrum:
    """Compute light neutrino mass spectrum from seesaw with cover-suppressed M_R.

    m_nu_i = (v * y_nu_i)^2 / M_R_i,  M_R_i = M_0 * A^(-2 i).
    """
    masses_eV: list[float] = []
    for i, y in enumerate(y_nu_pattern):
        M_R_i = M_0_GeV * A ** (-2 * i)
        m_D_i = v_GeV * y
        m_nu_i_GeV = (m_D_i * m_D_i) / M_R_i
        masses_eV.append(float(m_nu_i_GeV * 1e9))    # GeV -> eV

    masses_eV_sorted = sorted(masses_eV)
    delta_21 = masses_eV_sorted[1] ** 2 - masses_eV_sorted[0] ** 2
    delta_31 = masses_eV_sorted[2] ** 2 - masses_eV_sorted[0] ** 2
    return SeesawSpectrum(
        v_GeV=float(v_GeV),
        M_0_GeV=float(M_0_GeV),
        A=float(A),
        y_nu_pattern=tuple(float(y) for y in y_nu_pattern),
        light_masses_eV=(masses_eV_sorted[0], masses_eV_sorted[1], masses_eV_sorted[2]),
        sum_m_nu_eV=float(sum(masses_eV_sorted)),
        delta_m21_squared_eV2=float(delta_21),
        delta_m31_squared_eV2=float(delta_31),
        notes=("Standard seesaw with M_R ∝ A^(-2 winding). M_0 is an "
               "INPUT, not derived. Tune M_0 to match any sum_m_nu."),
    )


def m_0_required_for_sum(target_sum_eV: float = 0.06,
                          v_GeV: float = 246.22,
                          A: float = 0.48,
                          y_nu_pattern: tuple[float, float, float] = (1.0, 1.0, 1.0)) -> dict:
    """Reverse-engineer M_0 to produce the target sum (proof of TUNABLE)."""
    coeff = sum((y * y) * A ** (2 * i)
                for i, y in enumerate(y_nu_pattern))
    M_0_GeV = (v_GeV ** 2) * coeff * 1e9 / target_sum_eV
    return {
        "target_sum_eV": float(target_sum_eV),
        "M_0_required_GeV": float(M_0_GeV),
        "note": "M_0 is a free knob; any observed sum is reachable.",
    }


__all__ = [
    "SeesawSpectrum", "light_neutrino_spectrum", "m_0_required_for_sum",
]
